### ISSUE TITLE
Add a second fire button!

### ISSUE THREAD

**Issue by danko79** [RetroNynjah/Joystick-Tester#1]
Hi,I've been looking for this for some time! but can you make a version by adding the second fire button for Amiga?

**Comment by RetroNynjah** [comment]
The second button for the Amiga seems to be using pin 9 which is also used as one of the axes for paddles. I have an older version where I tested LEDs for pin 5 and pin 9 as a way to test paddles. Didn't work so I removed them to simplify the board.
Guess those would work for your second button though.
I have a few left from my first run. Do you need to manufacture them or do you need just one board?

**Comment by danko79** [comment]
Hi,i need a PCBs from you;
Amiga external floppy adapter
Amiga 500 ROM Adapter x2
Joystick-Tester
Do you have for sale?

**Comment by RetroNynjah** [comment]
I have some extra boards of all of those that I can send you.
Email me at retroninja_at_hofnet.com

**Comment by danko79** [comment]
Hi, reopen this, do you share a gerber for the Rev. 1?
